### ISSUE TITLE
Pie not rendering

### ISSUE THREAD

**Issue by l0stpenguin** [mkloubert/nativescript-taskpie#1]
Hi,
I just tried integrating your plugin into a fresh nativescript project based on [https://github.com/NativeScript/template-hello-world-ng](https://github.com/NativeScript/template-hello-world-ng)

I added the following codes to my page:
```xml
<StackLayout class="page" xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:taskPie="nativescript-taskpie">

      <taskPie:TaskPie id="mjk-test-taskpie"
                   counts="{{ taskCounts }}"
                   pieSize="350"
                   description="some description"
                   pieText="19 left"
                   pieSubText="a subtext" />

</StackLayout>
```
Added a taskCounts variable to my component.ts:
```typescript
public taskCounts = [11, 4, 1, 11];
```
I also added the required css to my app.css:
```css

.nsTaskPie-pieArea .nsTaskPie-textArea {
    margin-top: -16;
}

.nsTaskPie-pieArea .nsTaskPie-textArea .nsTaskPie-text {
    text-align: center;
    font-size: 40;
    color: #a6a6a6;
    padding: 0;
}

.nsTaskPie-pieArea .nsTaskPie-textArea .nsTaskPie-subText {
    text-align: center;
    font-size: 20;
    color: #a6a6a6;
    margin-top: -8;
    padding: 0;
}

.nsTaskPie-description {
    font-size: 20;
    margin-bottom: 12;
}

.nsTaskPie-categories .nsTaskPie-category {
    margin-left: 4;
    margin-right: 4;
}

.nsTaskPie-categories .nsTaskPie-border {
    height: 8;
}

.nsTaskPie-categories .nsTaskPie-count,
.nsTaskPie-categories .nsTaskPie-name,
.nsTaskPie-description {
    text-align: center;
    color: #333333;
}

.nsTaskPie-categories .nsTaskPie-count {
    font-size: 16;
    margin-top: 4;
}

.nsTaskPie-categories .nsTaskPie-name {
    font-size: 12;
}
```
When i run it on android, i get a blank page. Nothing is rendered and there is no error. Is there something i am missing?
